services:
  - type: web
    name: hulubalang-api
    runtime: docker
    dockerfilePath: ./Dockerfile.api
    plan: free
    region: singapore
    envVars:
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGINS
        value: "*"
